package testErr

import "errors"

var (
	// ErrESClusterNotFound ...
	ErrESClusterNotFound = errors.New("es cluster not found")

	// ErrESClusterNotConnected ...
	ErrESClusterNotConnected = errors.New("es cluster not connected")

	// ErrCreateLocalFile ...
	ErrCreateLocalFile = errors.New("failed to create local file")

	// ErrDownloadFile ...
	ErrDownloadFile = errors.New("failed to download file from s3")

	// ErrTenantNotFound ...
	ErrTenantNotFound = errors.New("tenant not found")

	// ErrESClusterForTenantNotFound ...
	ErrESClusterForTenantNotFound = errors.New("es cluster for the tenant not found")

	// ErrAppNotFound ...
	ErrAppNotFound = errors.New("app not found")

	// ErrFileSystemNotFound ...
	ErrFileSystemNotFound = errors.New("filesystem not found")

	// ErrConfigFileNotFound ...
	ErrConfigFileNotFound = errors.New("config file not found")

	// ErrLoadConfigFail ...
	ErrLoadConfigFail = errors.New("failed to load config file")

	// ErrIndexingTemplateNotFound ...
	ErrIndexingTemplateNotFound = errors.New("indexing template not found")

	// ErrUnmarshalMappingFail ...
	ErrUnmarshalMappingFail = errors.New("failed to unmarshal mapping")

	// ErrUpdateIndexingStatusUsedFail ...
	ErrUpdateIndexingStatusUsedFail = errors.New("failed to update indexing_status")

	// ErrUpdateIndexingStatusUsedConflict ...
	ErrUpdateIndexingStatusUsedConflict = errors.New("failed to update indexing_status, conflict")

	// ErrUpdateFSUsedFail ...
	ErrUpdateFSUsedFail = errors.New("failed to update fs_used")

	// ErrActionNotSupport ...
	ErrActionNotSupport = errors.New("action not support")

	// ErrPerformActionFail ...
	ErrPerformActionFail = errors.New("perform action fail")

	// ErrLoadAuditLine ...
	ErrLoadAuditLine = errors.New("failed to load audit line")

	// ErrAuditActionNotSupported ...
	ErrAuditActionNotSupported = errors.New("the audit action not supported")

	// ErrAuditNotSupported ...
	ErrAuditNotSupported = errors.New("the audit line not supported")

	// ErrIndexNotHealthy ...
	ErrIndexNotHealthy = errors.New("index not healthy")

	// ErrIndexNotFound ...
	ErrIndexNotFound = errors.New("index not found")

	// ErrESClusterNotAvailable ...
	ErrESClusterNotAvailable = errors.New("es cluster not available")

	// ErrTemplateNotFound ...
	ErrTemplateNotFound = errors.New("template not found")

	// ErrTemplateSettingIncorrect ...
	ErrTemplateSettingIncorrect = errors.New("template setting incorrect")

	// ErrCreateTemplate ...
	ErrCreateTemplate = errors.New("failed to create template")

	// ErrCreateIndexFail ...
	ErrCreateIndexFail = errors.New("failed to create index")

	// ErrGetIndexFail ...
	ErrGetIndexFail = errors.New("failed to get index")

	// ErrDeleteIndexFail ...
	ErrDeleteIndexFail = errors.New("failed to delete index")

	// ErrCloseIndexFail ...
	ErrCloseIndexFail = errors.New("failed to close index")

	// ErrCreateRepoFail ...
	ErrCreateRepoFail = errors.New("failed to create repo")

	// ErrCreateSnapshotFail ...
	ErrCreateSnapshotFail = errors.New("failed to create snapshot")

	// ErrRestoreSnapshotFail ...
	ErrRestoreSnapshotFail = errors.New("failed to restore snapshot")

	// ErrGetSnapshotFail ...
	ErrGetSnapshotFail = errors.New("failed to get snapshot")

	// ErrCheckSnapshotStatusFail ...
	ErrCheckSnapshotStatusFail = errors.New("failed to check snapshot status")

	// ErrLoadDataFail need to clean up
	ErrLoadDataFail = errors.New("failed to load all data")

	// ErrIndexFail need to clean up
	ErrIndexFail = errors.New("failed to index")

	// ErrIndexEmpty ...
	ErrIndexEmpty = errors.New("index is empty ")

	// ErrDeleteIndexByQuery ...
	ErrDeleteIndexByQuery = errors.New("failed to delete related data")
)
